name: Deploy Research Archive

on:
  workflow_dispatch:

env:
  # contentful
  NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
  NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
  NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
  NEXT_PUBLIC_CONTENTFUL_PREVIEW_SECRET: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_PREVIEW_SECRET }}
  NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT }}
  NEXT_PUBLIC_CONTENTFUL_GRAPHQL_ENDPOINT: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_GRAPHQL_ENDPOINT }}
  NEXT_PUBLIC_CONTENTFUL_ARCHIVE_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ARCHIVE_SPACE_ID }}
  NEXT_PUBLIC_CONTENTFUL_ARCHIVE_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ARCHIVE_ACCESS_TOKEN }}
  # firebase app settings
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
  # google
  NEXT_PUBLIC_GOOGLE_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_ID }}
  NEXT_PUBLIC_GOOGLE_SECRET: ${{ secrets.NEXT_PUBLIC_GOOGLE_SECRET }}
  # domains
  NEXT_PUBLIC_WEB_DOMAIN: ${{ secrets.NEXT_PUBLIC_WEB_DOMAIN }}
  NEXT_PUBLIC_API_DOMAIN: ${{ secrets.NEXT_PUBLIC_API_DOMAIN }}

jobs:
  deploy-research-app:
    name: Deploy research archive
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: export research-archive
        run: pnpm --dir apps/research-archive export
      - name: deploy research-archive
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GCP_SA_KEY }}'
          expires: 30d
          projectId: '${{ secrets.GCP_PROJECT_ID }}'
          channelId: live
          # removing target will deploy all targets defined in .firebaserc
          target: 'k33-research-archive'
