name: Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # turbo
          TURBO_TEAM: op://k33-web-env/prod/turbo/TEAM
          TURBO_TOKEN: op://k33-web-env/prod/turbo/TOKEN
          TURBO_REMOTE_ONLY: true
          # contentful
          NEXT_PUBLIC_CONTENTFUL_SPACE_ID: op://k33-web-env/prod/contentful/SPACE_ID
          NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: op://k33-web-env/prod/contentful/ACCESS_TOKEN
          NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN: op://k33-web-env/prod/contentful/PREVIEW_ACCESS_TOKEN
          NEXT_PUBLIC_CONTENTFUL_PREVIEW_SECRET: op://k33-web-env/prod/contentful/PREVIEW_SECRET
          NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT: op://k33-web-env/prod/contentful/ENVIRONMENT
          # firebase app settings
          NEXT_PUBLIC_FIREBASE_API_KEY: op://k33-web-env/prod/firebase/API_KEY
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: op://k33-web-env/prod/firebase/AUTH_DOMAIN
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: op://k33-web-env/prod/firebase/PROJECT_ID
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: op://k33-web-env/prod/firebase/STORAGE_BUCKET
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: op://k33-web-env/prod/firebase/MESSAGING_SENDER_ID
          NEXT_PUBLIC_FIREBASE_APP_ID: op://k33-web-env/prod/firebase/APP_ID
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: op://k33-web-env/prod/firebase/MEASUREMENT_ID
          # domains
          NEXT_PUBLIC_WEB_DOMAIN: op://k33-web-env/prod/domain/WEB
          NEXT_PUBLIC_API_DOMAIN: op://k33-web-env/prod/domain/API
          # algolia
          NEXT_PUBLIC_ALGOLIA_APP_ID: op://k33-web-env/prod/algolia/APP_ID
          NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: op://k33-web-env/prod/algolia/SEARCH_API_KEY
          # stripe
          ## this week in crypto
          NEXT_PUBLIC_STRIPE_PRODUCT_ID_TWIC: op://k33-web-env/prod/stripe/PRODUCT_ID_TWIC
          NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_TWIC: op://k33-web-env/prod/stripe/MONTHLY_PRICE_ID_TWIC
          NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_TWIC: op://k33-web-env/prod/stripe/YEARLY_PRICE_ID_TWIC
          ## navigating narratives
          NEXT_PUBLIC_STRIPE_PRODUCT_ID_NN: op://k33-web-env/prod/stripe/PRODUCT_ID_NN
          NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_NN: op://k33-web-env/prod/stripe/MONTHLY_PRICE_ID_NN
          NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_NN: op://k33-web-env/prod/stripe/YEARLY_PRICE_ID_NN
          ## ahead of the curve
          NEXT_PUBLIC_STRIPE_PRODUCT_ID_AOC: op://k33-web-env/prod/stripe/PRODUCT_ID_AOC
          NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_AOC: op://k33-web-env/prod/stripe/MONTHLY_PRICE_ID_AOC
          NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_AOC: op://k33-web-env/prod/stripe/YEARLY_PRICE_ID_AOC
          ## research pro
          NEXT_PUBLIC_STRIPE_PRODUCT_ID_PRO: op://k33-web-env/prod/stripe/PRODUCT_ID_PRO
          NEXT_PUBLIC_STRIPE_MONTHLY_PRICE_ID_PRO: op://k33-web-env/prod/stripe/MONTHLY_PRICE_ID_PRO
          NEXT_PUBLIC_STRIPE_YEARLY_PRICE_ID_PRO: op://k33-web-env/prod/stripe/YEARLY_PRICE_ID_PRO
          # analytics
          NEXT_PUBLIC_ANALYTICS_API_KEY: op://k33-web-env/prod/analytics/API_SECRET
      - name: Install dependencies
        run: pnpm install
      - name: Build local dependencies
        run: pnpm --dir packages/ui build
      - name: export auth
        run: pnpm --dir apps/auth export
      - name: export research
        run: pnpm --dir apps/research export
      - name: export invest
        run: pnpm --dir apps/invest export
      - name: export vault
        run: pnpm --dir apps/vault export
